### ISSUE TITLE
🐛 Bug Report: Getting Started in https://github.com/appwrite/sdk-for-dart contains a lot of bugs

### ISSUE THREAD

**Issue by Appwrite-Guru** [appwrite/sdk-for-dart#21]
### 👟 Reproduction steps

Open https://github.com/appwrite/sdk-for-dart and scroll to get started section. This code have a lot of bugs and its not valid dart code

import 'package:dart_appwrite/dart_appwrite.dart';

void main() async {
  Client client = Client();
    .setEndpoint('http://[HOSTNAME_OR_IP]/v1') // Make sure your endpoint is accessible
    .setProject('5ff3379a01d25') // Your project ID
    .setKey('cd868c7af8bdc893b4...93b7535db89')
    .setSelfSigned() // Use only on dev mode with a self-signed SSL cert

  Users users = Users(client);

  try {
    final response = await users.create(userId: '[USER_ID]', email: ‘email@example.com’,password: ‘password’, name: ‘name’);
    print(response.data);
  } on AppwriteException catch(e) {
    print(e.message);
  }
}

### 👍 Expected behavior

It should work

### 👎 Actual Behavior

It doesnt work

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by 2002Bishwajeet** [comment]
Can you share the stack trace of what's not working??

**Comment by tananga** [comment]
This whole example  section of code which is inside readme file is not a valid Dart code.

**Comment by 2002Bishwajeet** [comment]
Okay, I see what's the issue. 
it should be
```dart
Client client = Client()
.setEndpoint('http://[HOSTNAME_OR_IP]/v1') // Make sure your endpoint is accessible
.setProject('5ff3379a01d25') // Your project ID
.setKey('cd868c7af8bdc893b4...93b7535db89')
.setSelfSigned() // Use only on dev mode with a self-signed SSL cert
```
and not the one's in readme. I will drop a PR for this soon.

Till that time, I would recommend follow from the [appwrite docs](https://appwrite.io/docs/getting-started-for-server)

**Comment by tananga** [comment]
Thanks for help!

**Comment by 2002Bishwajeet** [comment]
This issue has been fixed. You can close this now

**Comment by tananga** [comment]
@2002Bishwajeet  This code is still not valid. 

Client client = Client();
    .setEndpoint('http://[HOSTNAME_OR_IP]/v1') // Make sure your endpoint is accessible
    .setProject('5ff3379a01d25') // Your project ID
    .setKey('cd868c7af8bdc893b4...93b7535db89')
    .setSelfSigned()

**Comment by 2002Bishwajeet** [comment]
```dart
Client client = Client(); --> There should be no semi-colon
.setEndpoint('http://[HOSTNAME_OR_IP]/v1') // Make sure your endpoint is accessible
.setProject('5ff3379a01d25') // Your project ID
.setKey('cd868c7af8bdc893b4...93b7535db89')
.setSelfSigned()
```

**Comment by tananga** [comment]
And ; at the end

**Comment by 2002Bishwajeet** [comment]
yup- a typo

**Comment by lohanidamodar** [comment]
This issue should now be fixed. Feel free to reopen if you still have issues.
